/*
A rotation of a string can be generated by moving characters one after another
from beginning to end. For example, the rotations of acab are acab, caba, abac, and baca.
Your task is to determine the lexicographically minimal rotation of a string.

Input

The only input line contains a string of length n. Each character is one of a–z.

Output

Print the lexicographically minimal rotation.

Constraints

1 <= n <= 10^6

Example
Input:
acab

Output:
abac
*/

#include <algorithm>
#include <iostream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

int main() {
    std::string inputString;
    std::cin >> inputString;
    int n = inputString.length();
    int m = 2 * n;
    std::string doubleString = inputString + inputString;

    // label, character index
    std::vector<std::pair<int, int>> singleLabels(m);
    // label pair left, right, and character index
    std::vector<std::tuple<int, int, int>> characterPairLabels(m);

    // initial single labels based on character order in the alphabet
    for (int i = 0; i < m; i++) {
        singleLabels[i] = {doubleString[i] - 'a' + 1, i};
    }

    for (int k = 1; k < n; k *= 2) {
        // create label pairs
        for (int i = 0; i < m; i++) {
            int second = i + k >= m ? 0 : singleLabels[i + k].first;
            characterPairLabels[i] = {singleLabels[i].first, second, i};
        }

        std::sort(characterPairLabels.begin(), characterPairLabels.end());

        // assign new labels based on label pairs
        int newLabel = 1;
        auto firstLabelTuple = characterPairLabels[0];
        // set first new label so next ones can compare to previous in the loop
        singleLabels[std::get<2>(firstLabelTuple)] = {newLabel, std::get<2>(firstLabelTuple)};

        for (int i = 1; i < m; i++) {
            auto labelTuple = characterPairLabels[i];
            auto left = std::get<0>(labelTuple);
            auto right = std::get<1>(labelTuple);
            auto charIndex = std::get<2>(labelTuple);

            auto prevTuple = characterPairLabels[i - 1];
            auto prevLeft = std::get<0>(prevTuple);
            auto prevRight = std::get<1>(prevTuple);

            if (left != prevLeft || right != prevRight) {
                newLabel++;
            }

            singleLabels[charIndex] = {newLabel, charIndex};
        }
    }

    std::sort(singleLabels.begin(), singleLabels.end());

    int best = -1;

    for (auto labelIndexPair : singleLabels) {
        int idx = labelIndexPair.second;
        if (idx < n) {
            best = idx;
            break;
        }
    }

    std::string rotated = doubleString.substr(best, n);
    std::cout << rotated << "\n";
}
